# Generated by Django 2.1.7 on 2019-02-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0006_auto_20190227_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='user_accounts/profile_pics'),
        ),
    ]
