# Generated by Django 2.1.7 on 2019-02-27 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0007_auto_20190227_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
    ]
