# Generated by Django 2.1.7 on 2019-02-25 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InitiativeTitle', models.CharField(max_length=200, unique=True)),
                ('requirements', models.TextField(default=' ')),
                ('name', models.CharField(max_length=100)),
                ('budget', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(default='', max_length=100)),
                ('details', models.TextField(default='No details abour this CSR event are present')),
                ('attendees', models.ManyToManyField(blank=True, related_name='attending', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
